apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: app1
  name: app1
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  labels:
    name: echo-service
    namespace: app1
spec:
  selector:
    matchLabels:
      name: echo-service
  template:
    metadata:
      labels:
        name: echo-service
        plane: control
    spec:
      containers:
        - name: app
          image: k8s.gcr.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    name: echo-service
  namespace: app1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: echo-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-service
  namespace: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - host: app1-autoscalling.ddns.net
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echo-service
                port:
                  number: 80
