apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: app2
  name: app2
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2
  labels:
    name: app2
spec:
  selector:
    matchLabels:
      name: app2
  template:
    metadata:
      labels:
        name: app2
        plane: control
    spec:
      containers:
        - name: app
          image: nginxdemos/hello
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 40m
              memory: 40Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    name: app2
  namespace: app2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: app2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  namespace: app2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app2.damien-jacinto.com
    external-dns.alpha.kubernetes.io/aws-region: eu-central-1
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: exemples
spec:
  ingressClassName: alb
  rules:
    - host: app2.damien-jacinto.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: app2
                port:
                  number: 80
