apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: app3
  name: app3
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: app3
  labels:
    name: app3
spec:
  selector:
    matchLabels:
      name: app3
  template:
    metadata:
      labels:
        name: app3
        plane: control
    spec:
      containers:
        - name: app
          image: k8s.gcr.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 400m
              memory: 400Mi
            limits:
              cpu: 800m
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  labels:
    name: app3
  namespace: app3
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: app3
