apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: app3
  namespace: app3
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: app3
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["cpu", "memory"]
